# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main_net8" ]
  pull_request:
    branches: [ "main_net8" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      PROJECT_DIR: 'src/Bl.QueryVisitor.MySql/Bl.QueryVisitor.MySql.csproj'
      
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release ${{ env.PROJECT_DIR }}
      
    - name: Pack
      run: dotnet pack --configuration Release --output nupkg ${{ env.PROJECT_DIR }}
      
    - name: Publish
      run: dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET }} --source https://api.nuget.org/v3/index.json
